---
# Stands up an ipsilon instance for simple SSO
- name: Configure Sigul Bridge
  hosts: sigulbridge
  become: true
  vars_files:
  - vars/vaults/encpass.yml
  - vars/common.yml
  - vars/sigul_bridge.yml

  # This is to try to avoid the handler issue in pre/post tasks
  handlers:
    - import_tasks: handlers/main.yml

  pre_tasks:
    - name: Check if ansible cannot be run here
      stat:
        path: /etc/no-ansible
      register: no_ansible

    - name: Verify if we can run ansible
      assert:
        that:
          - "not no_ansible.stat.exists"
        success_msg: "We are able to run on this node"
        fail_msg: "/etc/no-ansible exists - skipping run on this node"

    - name: Check for keytabs - sigul
      stat:
        path: /etc/sigul.keytab
      register: sigul_keytab_register
      changed_when: "1 != 1"

    - name: Verify keytab
      assert:
        that:
          - "sigul_keytab_register.stat.exists"
        success_msg: "It is likely we have all keytabs"
        fail_msg: "There are no keytabs. Please build the keytabs."

    # EPEL and PowerTools are required for ipsilon to function
    # I also couldn't find an ansible built-in to do this
    - name: Enable the PowerTools repository
      ini_file:
        dest: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
        section: powertools
        option: enabled
        value: 1
        owner: root
        group: root
        mode: '0644'

    # The CentOS extras repos has epel-release provided
    - name: Enable the EPEL repository
      yum:
        name: epel-release
        state: present
      tags:
        - packages

    - name: Install circle-tools copr
      yum_repository:
        name: copr:copr.fedorainfracloud.org:james6xie:circlelinux-tools
        description: Copr repo for circlelinux-tools owned by james6xie
        file: copr_repos
        baseurl: https://download.copr.fedorainfracloud.org/results/james6xie/circlelinux-tools/epel-8-$basearch/
        gpgcheck: true
        gpgkey: https://download.copr.fedorainfracloud.org/results/james6xie/circlelinux-tools/pubkey.gpg
        enabled: true

  roles:
    - role: circlelinux.sigul
      state: present

    - role: circlelinux.ipagetcert
      state: present

  post_tasks:
    - name: Enable the sigul bridge
      systemd:
        name: sigul_bridge
        state: restarted
        enabled: true

    - name: Touching run file that ansible has ran here
      file:
        path: /var/log/ansible.run
        state: touch
        mode: '0644'
        owner: root
        group: root
